#ifndef _SETTINGS_H
#define _SETTINGS_H

#define OPTICAL_CENTER_X 36.0
#define OPTICAL_CENTER_Y 32.5

#define MAX_PIXEL_VALUE_FOR_MAX_CALCULATION 2000

#define PA_MINIMUM_RADIUS 29.0
#define PA_MAXIMUM_RADIUS 38.0
#define PA_DY_FACTOR 0.7
#define PA_MINIMUM_VALUE 100
#define PA_ANGULAR_BIN_WIDTH 30
#define PA_ANGULAR_BIN_START 60.0
#define PA_ANGULAR_BIN_STOP 330.0
#define PA_ANGULAR_NUM_BINS 11
#define PA_ANGULAR_X0 20.0
#define PA_ANGULAR_Y0 32.5


#endif // _SETTINGS_H
